---
- name: Include common preflight tasks
  include_tasks: "common/preflight.yml"

- name: Include common installation tasks
  include_tasks: "common/install.yml"

- name: Include common configuration tasks
  include_tasks: "common/config.yml"

- name: Include common launch tasks
  include_tasks: "common/launch.yml"
