---
- name: Restart Elasticsearch service
  become: true
  service:
    name: elasticsearch
    state: restarted
  listen: Restart service

- name: Stop Elasticsearch systemd service
  service:
    name: elasticsearch
    state: stopped
    enabled: false
  listen: Uninstall service

- name: Remove Elasticsearch systemd service file
  become: true
  file:
    path: "/etc/systemd/system/elasticsearch.service"
    state: absent
  listen: Uninstall service

- name: Remove Elasticsearch install dir
  become: true
  file:
    path: "{{ install_dir }}"
    state: absent
  listen: Uninstall service

- name: Remove Elasticsearch config dir
  file:
    path: "{{ config_dir }}"
    state: absent
  become: true
  listen: Uninstall service

- name: Remove Elasticsearch data dir
  file:
    path: "{{ data_dir }}"
    state: absent
  become: true
  listen: Uninstall service

- name: Remove Elasticsearch logs dir
  file:
    path: "{{ logs_dir }}"
    state: absent
  become: true
  listen: Uninstall service

- name: Remove Elasticsearch user
  user:
    name: "{{ elasticsearch_user }}"
    state: absent
    remove: true
  listen: Uninstall service

- name: Remove Elasticsearch group
  group:
    name: "{{ elasticsearch_user }}"
    state: absent
  listen: Uninstall service
