---
- name: Create Elasticsearch config directory
  become: true
  file:
    path: "{{ config_dir }}"
    state: directory
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_user }}"

- name: Create Elasticsearch data directory
  become: true
  file:
    path: "{{ data_dir }}"
    state: directory
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_user }}"

- name: Create Elasticsearch log directory
  become: true
  file:
    path: "{{ logs_dir }}"
    state: directory
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_user }}"

- name: Copy elasticsearch.yml configuration in place
  become: true
  template:
    src: "{{ elasticsearch_config }}.j2"
    dest: "{{ config_dir|default(default_config_dir) }}/{{ elasticsearch_config }}"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_user }}"
    mode: 0644
  vars:
    conf: "{{ config }}"
  when: config is defined and config is not none
