---
- name: Determine installation directory
  set_fact:
    install_dir: '/usr/share/elasticsearch'
  when: install_type == "package"

- name: Determine configuration directory
  set_fact:
    config_dir: '/etc/elasticsearch'
  when: install_type == "package"

- name: Determine logs directory
  set_fact:
    logs_dir: "{{ config['path.logs']|default(config.path.logs)|default(logs_dir) }}"

- name: Determine data directory
  set_fact:
    data_dir: "{{ config['path.data']|default(config.path.data)|default(data_dir) }}"

- name: Set unit [Service] configuration
  set_fact:
    _default_service_unit:
      ExecStart: "{{ install_dir }}/bin/elasticsearch {{ extra_run_args|join(' ') }}"
      User: "{{ elasticsearch_user }}"
      Group: "{{ elasticsearch_user }}"
      StandardOutput: journal
      StandardError: inherit
